News.create title: "How many GeoNet staff does it take to upgrade a network site? "
News.create title: "The current eruption of Kīlauea: could it happen in Auckland? "
News.create title: "The Grand Canyon of Rotorua – a subterranean landslide in volcanic soil along an earthquake fault"
News.create title: "Never miss a GeoNet news story again"
News.create title: "Improvements to earthquake plots for the volcano team arrive on the GeoNet website"
News.create title: "Upcoming CWB Switch-Off is about keeping up with global best practice"
News.create title: "Tech Tales: Tim and Kris' Raoul Island Odyssey"
News.create title: "Minor seismic sequence over at Mt Ruapehu"
News.create title: "White Island (Whakaari); Crater Lake reforming and an earthquake swarm. Overall the volcano remains quiet. "
News.create title: "Slight increase in seismic activity at Mt Ruapehu"
